#!/usr/bin/env bash

[[ -n $TMUX ]] && change="switch-client" || change="attach-session"

if [[ -n $1 ]]; then
  tmux "$change" -t "$1" 2>/dev/null || {
    tmux new-session -d -s "$1" && tmux "$change" -t "$1"
  }
  exit 0
fi

session=$(tmux list-sessions -F "#{session_name}" 2>/dev/null |
  grep -v '^cursor' |
  fzf --exit-0 --header "Switch tmux session" --border=none) || exit 0

[[ -n $session ]] && tmux "$change" -t "$session"
