#!/usr/bin/env bash

[[ $- != *i* ]] && return

if [[ -z "$LANG" ]]; then
  eval "$(locale)"
fi

export EDITOR="nvim"
export VISUAL="$EDITOR"
export PAGER="less"
export LESSOPEN="| lessfilter %s"

shopt -s histappend
export HISTFILE="${XDG_STATE_HOME:-$HOME/.local/state}/bash/.bash_history"
mkdir -p "${XDG_STATE_HOME:-$HOME/.local/state}/bash"
HISTSIZE=10000
HISTFILESIZE=20000
HISTCONTROL=ignoreboth:erasedups
HISTTIMEFORMAT="%F %T "
HISTIGNORE="history:exit"

set -o notify
shopt -s checkwinsize
shopt -s globstar
shopt -s globstar
shopt -s extglob
shopt -s nullglob
shopt -s dotglob
shopt -s autocd
shopt -s cdspell
shopt -s dirspell

function has() { builtin command -v "$1" &>/dev/null; }
function is_macos() { [[ "$OSTYPE" = darwin* ]]; }
function is_linux() { [[ "$OSTYPE" = linux* ]]; }

# ls
if has eza; then
  alias l="eza --git"
  alias ll="l -lao --group-directories-first"
  alias ld="l -lD"
  alias lf="l -lf"
  alias lh="l -ld .* --group-directories-first"
  alias lt="l -la --sort=modified --reverse"
  alias ls="ll"
  alias lsg="l -ao --group-directories-first --grid"
fi

if is_linux; then
  [[ $PS1 &&
    ! ${BASH_COMPLETION_VERSINFO:-} &&
    -f /usr/share/bash-completion/bash_completion ]] &&
    . /usr/share/bash-completion/bash_completion
fi

if is_macos; then
  if [[ -s /opt/homebrew/etc/profile.d/bash_completion.sh ]]; then
    . "/opt/homebrew/etc/profile.d/bash_completion.sh"
  fi
fi

BASH_COMPLETION_USER_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/bash/completions"
if [[ -d "$BASH_COMPLETION_USER_DIR" ]]; then
  for f in "$BASH_COMPLETION_USER_DIR"/*; do
    source "$f"
  done
fi

if has mise; then
  eval "$(mise activate bash)"
fi

if has fzf; then
  eval "$(fzf --bash)"
fi

if has zoxide; then
  eval "$(zoxide init bash)"
fi
