#!/usr/bin/env bash

if [[ -z "$LANG" ]]; then
  eval "$(locale)"
fi

export EDITOR="nvim"
export VISUAL="$EDITOR"
export PAGER="less"

if builtin command -v mise >/dev/null 2>&1; then
  eval "$(mise activate bash)"
fi
