#!/usr/bin/env sh

if [ "$BASH" ]; then
  if [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
  fi
fi

export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-$HOME/.xdg}"
export XDG_PROJECTS_DIR="${XDG_PROJECTS_DIR:-$HOME/Projects}"

path_add() {
  case ":$PATH:" in
  *:"$1":*) ;;
  *) PATH="$1:$PATH" ;;
  esac
}

path_add /usr/local/bin
path_add /usr/local/sbin
path_add /usr/bin
path_add /usr/sbin
path_add /bin
path_add /sbin
path_add "$HOME/.local/bin"

export FZF_DEFAULT_OPTS="--tmux=80% \
--layout=reverse \
--highlight-line \
--cycle \
--bind=ctrl-f:preview-half-page-down,ctrl-b:preview-half-page-up,alt-j:preview-down,alt-k:preview-up \
--color=border:#27a1b9
"
export RIPGREP_CONFIG_PATH="${XDG_CONFIG_HOME:-$HOME/.config}/ripgrep/config"
