#!/usr/bin/env sh

path_add() {
  case ":$PATH:" in
  *:"$1":*) ;;
  *) PATH="$1:$PATH" ;;
  esac
}

path_add /usr/local/bin
path_add /usr/local/sbin
path_add /usr/bin
path_add /usr/sbin
path_add /bin
path_add /sbin
path_add "$HOME/.local/bin"
