#!/usr/bin/env zsh

cd() {
  emulate -L zsh

  if (($# == 0)); then
    local git_root

    git_root=$(command git rev-parse --show-toplevel 2> /dev/null)

    if [[ -n $git_root && $PWD != $git_root ]]; then
      builtin cd -- "$git_root"
    else
      builtin cd -- "$HOME"
    fi

    return
  fi

  if [[ $1 == -[!-]* ]] || (($# > 1)); then
    builtin cd "$@"

    return
  fi

  local target=$1

  if [[ $target == '-' || -d $target ]]; then
    builtin cd -- "$target"

    return
  fi

  if [[ -f $target ]]; then
    builtin cd -- "${target:h}"

    return
  fi

  if [[ $target == <-> ]]; then
    if ((target == 0)); then
      local git_root
      git_root=$(command git rev-parse --show-toplevel 2> /dev/null)

      if [[ -n $git_root ]]; then
        builtin cd -- "$git_root"
      else
        builtin cd -- '..'
      fi
    else
      local dots='.'
      local -i i

      for ((i = 0; i < target; ++i)); do
        dots+='/..'
      done

      builtin cd -- "$dots"
    fi
    return
  fi

  if (($+functions[z])); then
    z "$@" 2> /dev/null || builtin cd -- "$@"
  else
    builtin cd -- "$@"
  fi
}
