#!/usr/bin/env sh

copypath() {
  _file=${1:-.}

  case $_file in
  /*) _path=$_file ;;
  *) _path=$PWD/$_file ;;
  esac

  if [ -d "$_path" ]; then
    _abs_path=$(cd "$_path" 2>/dev/null && pwd) || return 1
  else
    _dir=$(dirname "$_path")
    _base=$(basename "$_path")
    _abs_path=$(cd "$_dir" 2>/dev/null && pwd)/$_base || return 1
  fi

  printf '%s' "$_abs_path" | pbcopy || return 1
  echo "$_abs_path copied to clipboard."
}
