#!/usr/bin/env zsh

create-alias() {
  emulate -L zsh

  typeset -gaU ealiases
  typeset -gaU baliases
  typeset -gA alias_descriptions

  local -i expand=0 blank=0 global=0 print_description=0
  local description='' definition key

  while (($#)); do
    case $1 in
      -e | --expand)
        expand=1
        ;;
      -b | --blank)
        blank=1
        ;;
      -g | --global)
        global=1
        ;;
      -p | --print)
        print_description=1
        ;;
      -d | --description)
        (($# >= 2)) || {
          print -u2 -- "create-alias: $1 requires an argument"
          return 1
        }
        description=$2
        shift
        ;;
      -cs | --cheatsheet)
        local -a lines

        local key_color=$'\e[38;5;4m'
        local desc_color=$'\e[38;5;15m'
        local reset=$'\e[0m'

        for key in ${(ok)alias_descriptions}; do
          lines+=("${key_color}${key}${reset} - ${desc_color}${alias_descriptions[$key]}${reset}")
        done

        if (("${+TMUX}")); then
          local tmpfile="$(mktemp)"

          print -rl -- "$lines[@]" >| "$tmpfile"

          command tmux popup -w '90%' -h '90%' -E \
            "zsh -c 'exec cat ${tmpfile} | less -R'"

          command rm -f -- "$tmpfile"
        else
          print -rl -- "$lines[@]" | "${PAGER:-less}"
        fi
        return 0
        ;;
      --)
        shift
        break
        ;;
      -*)
        print -u2 -- "create-alias: unknown option: $1"
        return 1
        ;;
      *)
        break
        ;;
    esac

    shift
  done

  if ((print_description)); then
    (($# == 1)) || {
      print -u2 -- 'Usage: create-alias --print name'
      return 1
    }
    [[ -n ${alias_descriptions[$1]} ]] || {
      print -u2 -- "create-alias: no description for: $1"
      return 1
    }
    print -- "${alias_descriptions[$1]}"
    return
  fi

  (($# == 1)) || {
    print -u2 -- 'Usage: create-alias [options] name=value'
    return 1
  }

  definition=$1

  [[ $definition == *=* ]] || {
    print -u2 -- "create-alias: expected name=value, got: $definition"
    return 1
  }

  key=${definition%%=*}

  [[ -n $key ]] || {
    print -u2 -- 'create-alias: alias name cannot be empty'
    return 1
  }

  if ((global)); then
    alias -g -- "$definition" || return
  else
    alias -- "$definition" || return
  fi

  ((expand)) && ealiases+=("$key")
  ((blank)) && baliases+=("$key")

  if [[ -n $description ]]; then
    alias_descriptions[$key]=$description
  else
    unset "alias_descriptions[$key]"
  fi
}
