#!/usr/bin/env sh

# Select a running docker container and attach interactively to it
dai() {
  if ! docker ps -q | grep -q .; then
    echo "No docker containers running!"
    return 1
  fi

  if [ -n "$1" ]; then
    _cid="$(docker ps -q --filter "name=$1" | head -n1)"
  else
    _cid="$(
      docker ps --format "{{.ID}}\t{{.Names}}\t{{.Image}}\t{{.Status}}" |
        fzf -1 |
        awk '{print $1}'
    )" || return 1
  fi

  if [ -z "$_cid" ]; then
    echo "Couldn't find container id"
    return 1
  fi

  docker exec -e TERM -e COLORTERM -e LC_ALL=C.UTF-8 -it "$_cid" sh -c "if [ -x /bin/bash ]; then exec /bin/bash; else exec /bin/sh; fi"

  unset _cid
}
