#!/usr/bin/env sh

gco() {
  if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    echo "Not in git repository!"
    return 1
  fi

  _branches="$(
    git for-each-ref \
      --count=30 \
      --sort=-committerdate \
      refs/heads/ \
      --format='%(refname:short)'
  )"

  if [ -z "$_branches" ]; then
    echo "No branches found"
    return 1
  fi

  _branch="$(
    printf '%s\n' "$_branches" | fzf
  )" || return 1

  git checkout "$_branch"

  unset _branches _branch
}
