#!/usr/bin/env zsh

imgtojpg() {
  emulate -L zsh

  if (($# == 0)); then
    print -u2 'Usage: imgtojpg <image_file> [image_file...]'
    return 1
  fi

  local cmd
  if (($+commands[magick])); then
    cmd="magick"
  elif (($+commands[convert])); then
    cmd="convert"
  else
    print -u2 'imgtojpg: ImageMagick (magick/convert) is not installed.'
    return 1
  fi

  local file target_name
  for file in "$@"; do
    if [[ ! -f $file ]]; then
      print -u2 "imgtojpg: file not found: $file"
      continue
    fi

    target_name="${file:r}.jpg"

    "$cmd" "$file" -quality 100 "$target_name" &&
      print -r "Converted: $file -> $target_name"
  done
}
