#!/usr/bin/env zsh

plugin::_validate_repo() {
  local repo=$1 cmd=$2

  [[ -n $repo ]] || {
    print -u2 -P "%F{red}Usage:%f plugin ${cmd} owner/repository"
    return 2
  }

  [[ $repo == */* && $repo != */*/* ]] || {
    print -u2 -P "%F{red}Invalid plugin:%f ${repo}"
    print -u2 -P 'Expected: %F{yellow}owner/repository%f'
    return 2
  }
}

plugin::_find_entry() {
  emulate -L zsh
  setopt local_options extended_glob

  local target=$1 name=$2 out_var=$3
  local -a entries=(
    "$target/$name.plugin.zsh"
    "$target"/*.plugin.zsh(N)
    "$target/$name.zsh-theme"
    "$target"/*.zsh-theme(N)
    "$target/$name.zsh"
  )

  local _candidate
  for _candidate in $entries; do
    [[ -r $_candidate ]] && {
      : ${(P)out_var::=$_candidate}
      return 0
    }
  done
  return 1
}

plugin::clone() {
  emulate -L zsh
  setopt local_options extended_glob

  zmodload -m -F zsh/files 'b:zf_*'

  local repo= source_after=0
  local arg
  for arg in "$@"; do
    case $arg in
      --source) source_after=1 ;;
      *) repo=$arg ;;
    esac
  done

  plugin::_validate_repo "$repo" clone || return $?

  local plugins_dir=${ZSH_PLUGINS_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/zsh/plugins}
  local name=${repo:t}
  local target="${plugins_dir}/${name}"

  if [[ ! -d $target ]]; then
    zf_mkdir -p -- "$plugins_dir" || {
      print -u2 -P "%F{red}✗ Cannot create:%f $plugins_dir"
      return 1
    }

    print -u2 -P "Installing %F{magenta}${repo}%f..."

    if ! command git clone \
      -q \
      --depth 1 \
      --recursive \
      --shallow-submodules \
      -- "https://github.com/${repo}.git" \
      "$target"; then
      zf_rm -rf -- "$target"
      print -u2 -P "%F{red}✗ Failed to install%f ${repo}"
      return 1
    fi
    print -u2 -P "%F{green}✓ Installed%f ${repo}"
  elif [[ ! -d $target/.git ]]; then
    print -u2 -P "%F{red}✗ Not a Git repository:%f $target"
    return 1
  fi

  local entry
  plugin::_find_entry "$target" "$name" entry || {
    print -u2 -P "%F{red}✗ Missing plugin entrypoint:%f ${repo}"
    print -u2 -- "  $target"
    return 1
  }

  ZSH_PLUGIN_ENTRY[$name]=$entry
  ZSH_PLUGIN_REPO[$name]=$repo

  ((source_after)) && plugin::source "$repo"
}

plugin::source() {
  emulate -L zsh
  setopt local_options extended_glob

  local repo=${1:-}
  plugin::_validate_repo "$repo" source || return $?

  local name=${repo:t}
  local entry=$ZSH_PLUGIN_ENTRY[$name]

  if [[ -z $entry ]]; then
    local plugins_dir=${ZSH_PLUGINS_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/zsh/plugins}
    local target="${plugins_dir}/${name}"

    [[ -d $target ]] || {
      print -u2 -P "%F{red}✗ Not installed:%f ${repo}"
      print -u2 -P "  Run: %F{yellow}chezmoi apply%f"
      return 1
    }

    plugin::_find_entry "$target" "$name" entry || {
      print -u2 -P "%F{red}✗ Missing plugin entrypoint:%f ${repo}"
      print -u2 -- "  $target"
      return 1
    }

    ZSH_PLUGIN_ENTRY[$name]=$entry
    ZSH_PLUGIN_REPO[$name]=$repo
  fi

  source "$entry"
  ZSH_PLUGIN_LOADED[$name]=1
}

plugin::update() {
  emulate -L zsh
  setopt local_options extended_glob

  local plugins_dir=${ZSH_PLUGINS_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/zsh/plugins}
  local -a targets
  local target name ret=0

  if [[ -n $1 ]]; then
    plugin::_validate_repo "$1" update || return $?

    target="${plugins_dir}/${1:t}"
    [[ -d $target ]] || {
      print -u2 -P "%F{red}✗ Not installed:%f ${1}"
      return 1
    }
    targets=("$target")
  else
    targets=(${plugins_dir}/*(N/))
  fi

  [[ ${#targets} -gt 0 ]] || {
    print -u2 -P "%F{yellow}No plugins installed%f"
    return 0
  }

  for target in $targets; do
    name=${target:t}

    [[ -d $target/.git ]] || {
      print -u2 -P "%F{red}✗ Not a Git repository:%f $target"
      ret=1
      continue
    }

    print -u2 -P "Updating %F{magenta}${name}%f..."
    if command git -C "$target" pull -q --ff-only --recurse-submodules; then
      print -u2 -P "%F{green}✓ Updated%f ${name}"
    else
      print -u2 -P "%F{red}✗ Failed to update%f ${name}"
      ret=1
    fi
  done

  return $ret
}

plugin::list() {
  emulate -L zsh
  setopt local_options extended_glob

  local plugins_dir=${ZSH_PLUGINS_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/zsh/plugins}
  local -a targets=(${plugins_dir}/*(N/))

  [[ ${#targets} -gt 0 ]] || {
    print -u2 -P "%F{yellow}No plugins installed%f"
    return 0
  }

  local target name repo state
  for target in $targets; do
    name=${target:t}

    repo=${ZSH_PLUGIN_REPO[$name]:-$(command git -C "$target" remote get-url origin 2> /dev/null)}
    repo=${repo#https://github.com/}
    repo=${repo%.git}

    if [[ -n ${ZSH_PLUGIN_LOADED[$name]:-} ]]; then
      state='%F{green}loaded%f'
    else
      state='%F{yellow}not loaded%f'
    fi

    print -P "%F{magenta}${name}%f${repo:+ (${repo})} - ${state}"
  done
}

plugin() {
  emulate -L zsh

  typeset -gA ZSH_PLUGIN_ENTRY
  typeset -gA ZSH_PLUGIN_LOADED
  typeset -gA ZSH_PLUGIN_REPO

  local cmd=$1
  shift
  case "$cmd" in
    clone) plugin::clone "$@" ;;
    source) plugin::source "$@" ;;
    update) plugin::update "$@" ;;
    list) plugin::list "$@" ;;
    *)
      print -u2 "plugin: unknown subcommand '$cmd' (clone|source|update|list)"
      return 1
      ;;
  esac
}

plugin "$@"
