#!/usr/bin/env bash

function copyfile {
  emulate -L zsh

  if [[ -z "$1" ]]; then
    echo "Usage: copyfile <file>"
    return 1
  fi

  if [[ ! -f "$1" ]]; then
    echo "Error: '$1' is not a valid file."
    return 1
  fi

  cat $1 | pbcopy || return 1

  echo "File copied to clipboard!"

  return 0
}
