#!/usr/bin/env bash

# Select a docker container to start and attach interactively to it
function dai() {
  local cid
  cid=$(docker ps | sed 1d | fzf -1 -q "$1" | awk '{print $1}')

  docker exec -it "$cid" "/bin/sh"
}
