#!/usr/bin/env zsh

if [[ -z "$LANG" ]]; then
  eval "$(locale)"
fi

export EDITOR="nvim"
export VISUAL="$EDITOR"
export PAGER="less"
export LESSOPEN="| lessfilter %s"

export ZSTATEDIR="${XDG_STATE_HOME:-$HOME/.local/state}/zsh"
export ZSHAREDIR="${XDG_SHARE_HOME:-$HOME/.local/share}/zsh"
export ZCACHEDIR="${XDG_CACHE_HOME:-$HOME/.cache}/zsh"
export ZPLUGINDIR="${ZSHAREDIR:-$HOME/.local/share/zsh}/plugins"
export ZCOMPDUMP="$ZCACHEDIR/zcompdump-$ZSH_VERSION"
export ZCOMPDIR="${ZDOTDIR:-$XDG_CONFIG_HOME/zsh}/completions"
export ZFUNCDIR="${ZDOTDIR:-$XDG_CONFIG_HOME/zsh}/functions"

z_dirs=(
  "$ZSTATEDIR"
  "$ZSHAREDIR"
  "$ZCACHEDIR"
)
for dir in $z_dirs; do
  [[ ! -d "$dir" ]] && mkdir -p "$dir"
done
unset z_dirs

typeset -U path fpath cdpath

path=(
  "/usr/local/bin"
  "/usr/local/sbin"
  "/usr/bin"
  "/usr/sbin"
  "/bin"
  "/sbin"
  "$HOME/.local/bin"
  "$path"
)

fpath+=(
  "$ZCOMPDIR"
  "$ZFUNCDIR"
)

cdpath+=(
  "${XDG_PROJECTS_DIR:-$HOME/Projects}"
)
