#!/usr/bin/env zsh

[[ -o 'interactive' ]] || return

if (($+ZSH_PROFILE)); then zmodload zsh/zprof; fi

source "$ZSH_CONFIG_HOME/zshrc.d/environment.zsh"
source "$ZSH_CONFIG_HOME/zshrc.d/setopt.zsh"
source "$ZSH_CONFIG_HOME/zshrc.d/history.zsh"

autoload -Uz ${ZSH_FUNCTIONS_DIR:-$ZDOTDIR/functions}/*(N.:t)

plugin-source() {
  local plugin="$1"
  local file="$ZSH_PLUGINS_DIR/$plugin/$plugin.plugin.zsh"
  [[ -r $file ]] || {
    print -u2 "zshrc: missing plugin '$plugin' (run: chezmoi apply)"
    return 1
  }
  source "$file"
}

plugin-source zsh-defer || function zsh-defer {
  while [[ $1 == -[acmpt]* ]]; do
    [[ $1 == -c ]] && {
      shift
      eval "$1"
      return
    }
    shift 2
  done
  "$@"
}

zsh-defer -c '
  run-compinit
  plugin-source fzf-tab
  plugin-source zsh-autopair
  plugin-source zsh-autosuggestions
  plugin-source fast-syntax-highlighting
  (( $+commands[mise] )) && source <(mise activate zsh)
  (( $+commands[fzf] )) && source <(fzf --zsh)
  (( $+commands[zoxide] )) && source <(zoxide init zsh)
  (( $+commands[gdircolors] )) &&
    [[ -r "$XDG_CONFIG_HOME/dircolors/tokyonight.dircolors" ]] &&
    source <(gdircolors -b "$XDG_CONFIG_HOME/dircolors/tokyonight.dircolors")
'

source "$ZSH_CONFIG_HOME/zshrc.d/prompt.zsh"
source "$ZSH_CONFIG_HOME/zshrc.d/completion.zsh"
source "$ZSH_CONFIG_HOME/zshrc.d/editor.zsh"

zsh-defer source "$ZSH_CONFIG_HOME/zshrc.d/gnu_coreutils.zsh"
zsh-defer source "$ZSH_CONFIG_HOME/zshrc.d/fzf.zsh"

zsh-defer source "$ZSH_CONFIG_HOME/zshrc.d/alias.zsh"

if (($+ZSH_PROFILE)); then builtin zprof; fi
