#!/usr/bin/env zsh

export EDITOR="nvim"
export VISUAL="$EDITOR"
export PAGER="less"
export LESSOPEN="| lessfilter %s"

export ZSTATEDIR="${XDG_STATE_HOME:-$HOME/.local/state}/zsh"
export ZSHAREDIR="${XDG_SHARE_HOME:-$HOME/.local/share}/zsh"
export ZCACHEDIR="${XDG_CACHE_HOME:-$HOME/.cache}/zsh"
export ZPLUGINDIR="${ZSHAREDIR:-$HOME/.local/share/zsh}/plugins"
export ZCOMPDUMP="$ZCACHEDIR/zcompdump-$ZSH_VERSION"
export ZCOMPDIR="${ZDOTDIR:-$XDG_CONFIG_HOME/zsh}/completions"
export ZFUNCDIR="${ZDOTDIR:-$XDG_CONFIG_HOME/zsh}/functions"

z_dirs=(
  "$ZSTATEDIR"
  "$ZSHAREDIR"
  "$ZCACHEDIR"
)
for dir in $z_dirs; do
  [[ ! -d "$dir" ]] && mkdir -p "$dir"
done
unset z_dirs

typeset -gU path fpath cdpath manpath mailpath
typeset -gUT INFOPATH infopath

for path_file in /etc/paths.d/*(.N); do
  path+=($(<$path_file))
done
unset path_file

fpath=(
  "$ZCOMPDIR"
  "$ZFUNCDIR"
  $fpath
)

cdpath=(
  "${XDG_PROJECTS_DIR:-$HOME/Projects}"
  $cdpath
)

manpath=(
  "/usr/local/share/man"
  "/usr/share/man"
  $manpath
)
for manpath_file in /etc/manpaths.d/*(.N); do
  manpath+=($(<$manpath_file))
done
unset manpath_file

infopath=(
  "/usr/local/share/info"
  "/usr/share/info"
  $infopath
)

if [[ "$OSTYPE" = darwin* ]]; then
  path=(
    "/opt/homebrew/bin"
    "/opt/homebrew/sbin"
    $path
  )
  fpath=(
    "/opt/homebrew/share/zsh/site-functions"
    $fpath
  )
  infopath=(
    "/opt/homebrew/share/info"
    $infopath
  )

  export HOMEBREW_PREFIX="/opt/homebrew"
  export HOMEBREW_CELLAR="/opt/homebrew/Cellar"
  export HOMEBREW_REPOSITORY="/opt/homebrew"
fi

if [[ -z "$LANG" ]]; then
  eval "$(locale)"
fi
