#!/usr/bin/env zsh

unsetopt globalrcs

typeset -gU path

path=(
  "/usr/local/bin"
  "/usr/local/sbin"
  "/usr/bin"
  "/usr/sbin"
  "/bin"
  "/sbin"
  "$HOME/.local/bin"
  $path
)

function has() { builtin command -v "$1" &>/dev/null; }
function is_macos() { [[ "$OSTYPE" = darwin* ]]; }
function is_linux() { [[ "$OSTYPE" = linux* ]]; }
