#!/usr/bin/env zsh

eval "$(/opt/homebrew/bin/brew shellenv)"

export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

export EDITOR="nvim"
export VISUAL="$EDITOR"
export PAGER="less"
export LESSOPEN="| lessfilter %s"

export ZSTATEDIR="${XDG_STATE_HOME:-$HOME/.local/state}/zsh"
export ZSHAREDIR="${XDG_SHARE_HOME:-$HOME/.local/share}/zsh"
export ZCACHEDIR="${XDG_CACHE_HOME:-$HOME/.cache}/zsh"
export ZPLUGINDIR="${ZSHAREDIR:-$HOME/.local/share/zsh}/plugins"
export ZCOMPDUMP="$ZCACHEDIR/zcompdump-$ZSH_VERSION"
export ZCOMPDIR="${ZDOTDIR:-$XDG_CONFIG_HOME/zsh}/completions"
export ZFUNCDIR="${ZDOTDIR:-$XDG_CONFIG_HOME/zsh}/functions"

local z_dirs=(
  "$ZSTATEDIR"
  "$ZSHAREDIR"
  "$ZCACHEDIR"
)

for dir in $z_dirs; do
  [[ ! -d "$dir" ]] && mkdir -p "$dir"
done

typeset -U fpath cdpath

fpath+=(
  "$ZCOMPDIR"
  "$ZFUNCDIR"
)

cdpath+=(
  "${XDG_PROJECTS_DIR:-$HOME/Projects}"
)
