require("devastion.core.globals")
require("devastion.core.options")
require("devastion.core.filetypes")
require("devastion.core.autocmds")
require("devastion.core.usercmds")
require("devastion.core.keymaps")

require("devastion.plugins.tokyonight")

vim.pack.add({ "https://github.com/nvim-mini/mini.nvim" }, { confirm = false })
require("mini.notify").setup()
vim.notify = require("mini.notify").make_notify()

require("mini.icons").setup()
require("mini.icons").mock_nvim_web_devicons()
require("mini.icons").tweak_lsp_kind()

require("devastion.plugins.scope")
require("devastion.plugins.auto-session")
require("devastion.plugins.treesitter")
require("devastion.plugins.which-key")
require("devastion.plugins.mini")
require("devastion.plugins.bufferline")
require("devastion.plugins.mason")
require("devastion.plugins.conform")
require("devastion.plugins.lint")
require("devastion.plugins.fzf")
require("devastion.plugins.blink")
require("devastion.plugins.flash")
require("devastion.plugins.noice")
require("devastion.plugins.lualine")
require("devastion.plugins.yanky")
require("devastion.plugins.bqf")
require("devastion.plugins.todo-comments")
require("devastion.plugins.gitsigns")
require("devastion.plugins.neotest")
require("devastion.plugins.grug-far")
require("devastion.plugins.neogen")
require("devastion.plugins.arrow")
require("devastion.plugins.git-conflict")
require("devastion.plugins.stay-centered")
require("devastion.plugins.highlight-colors")
require("devastion.plugins.inc-rename")
require("devastion.plugins.guess-indent")
