if vim.loader then
  vim.loader.enable()
end

require("devastion.core.globals")
require("devastion.core.options")
require("devastion.core.filetypes")
require("devastion.core.autocmds")
require("devastion.core.usercmds")
require("devastion.core.keymaps")
require("devastion.core.lsp")

require("devastion.plugins.tokyonight")

vim.pack.add({ "https://github.com/nvim-mini/mini.icons" }, { confirm = false })
require("mini.icons").setup()
require("mini.icons").mock_nvim_web_devicons()
require("mini.icons").tweak_lsp_kind()

require("devastion.plugins.treesitter")
require("devastion.plugins.scope")
require("devastion.plugins.auto-session")
require("devastion.plugins.snacks")
require("devastion.plugins.noice")
require("devastion.plugins.which-key")
require("devastion.plugins.mini")
require("devastion.plugins.bufferline")
require("devastion.plugins.mason")
require("devastion.plugins.conform")
require("devastion.plugins.lint")
require("devastion.plugins.fzf")
require("devastion.plugins.blink")
require("devastion.plugins.flash")
require("devastion.plugins.lualine")
require("devastion.plugins.yanky")
require("devastion.plugins.bqf")
require("devastion.plugins.todo-comments")
require("devastion.plugins.gitsigns")
require("devastion.plugins.spider")
require("devastion.plugins.neotest")
require("devastion.plugins.grug-far")
require("devastion.plugins.neogen")
require("devastion.plugins.arrow")
require("devastion.plugins.git-conflict")
require("devastion.plugins.stay-centered")
require("devastion.plugins.highlight-colors")
require("devastion.plugins.inc-rename")
require("devastion.plugins.guess-indent")
require("devastion.plugins.live-command")
require("devastion.plugins.dap")
require("devastion.plugins.refactoring")
require("devastion.plugins.coverage")
require("devastion.plugins.navic")
require("devastion.plugins.workspace-diagnostics")
require("devastion.plugins.package-info")
require("devastion.plugins.venv-selector")
require("devastion.plugins.vim-tmux-navigator")
require("devastion.plugins.vim-fugitive")
-- require("devastion.plugins.vim-wordmotion")
