[tools]
"asdf:neovim" = "nightly"
ast-grep = "latest"
bat = "latest"
delta = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
hadolint = "latest"
jq = "latest"
lua = "latest"
node = "latest"
ripgrep = "latest"
rust = "latest"
stylua = "latest"
tree-sitter = "latest"
zoxide = "latest"
