[tools]
ast-grep = "latest"
bat = "latest"
go = "latest"
java = "latest"
node = "lts"
python = "latest"
rust = "stable"
usage = "latest"
delta = "latest"
eza = "latest"
fzf = "latest"
jq = "latest"
lazygit = "latest"
ripgrep = "latest"
tlrc = "latest"
tmux = "latest"
yq = "latest"
zoxide = "latest"
gitleaks = "latest"
fd = "latest"
watchexec = "latest"
"go:github.com/reteps/dockerfmt" = "latest"
neovim = "nightly"
pkl = "latest"

[settings]
lockfile = true
experimental = true
idiomatic_version_file_enable_tools = ["node"]
